# Generated by Django 5.0.1 on 2024-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_geofencedarea_mark_attendance_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_attendance_report',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
