# Generated by Django 5.0.1 on 2024-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_mark_attendance_report_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_attendance_report',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
