# Generated by Django 5.0.1 on 2025-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_mark_attendance_report_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_leave_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=100)),
                ('Emp_name', models.CharField(max_length=100)),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee_register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='employee_image_encodeing',
            field=models.BinaryField(null=True),
        ),
    ]
