# Generated by Django 5.0.1 on 2025-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_employee_leave_data_employee_register_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='grant_leave_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=100)),
                ('Emp_name', models.CharField(max_length=100)),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('grant', models.BooleanField()),
            ],
        ),
    ]
