# Generated by Django 5.0.1 on 2025-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_grant_leave_model_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant_leave_model',
            name='Emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant_leave_model',
            name='Emp_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant_leave_model',
            name='from_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant_leave_model',
            name='grant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='grant_leave_model',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant_leave_model',
            name='to_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
