# Generated by Django 5.0.1 on 2025-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_delete_grant_leave_model_employee_leave_data_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salary_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=100)),
                ('Emp_name', models.CharField(max_length=100)),
                ('Month', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
