# Generated by Django 5.0.1 on 2025-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_employee_salary_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_register_table',
            old_name='employee_mobile_number',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='payroll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
