# Generated by Django 5.0.1 on 2025-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_rename_employee_mobile_number_employee_register_table_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
