# Generated by Django 5.0.1 on 2025-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_employee_details_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_attendance_report',
            name='date',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
